# render.yaml for Unity WebGL + React + Brotli
staticPublishPath: ./dist

headers:
  # Unity .data.br files
  - path: /unity/Build/webBuild.data.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.data.br
    name: Content-Type
    value: application/octet-stream

  # Unity .framework.js.br files
  - path: /unity/Build/webBuild.framework.js.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.framework.js.br
    name: Content-Type
    value: application/javascript

  # Unity .wasm.br files
  - path: /unity/Build/webBuild.wasm.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.wasm.br
    name: Content-Type
    value: application/wasm

  # Optional: if you have other Unity files that are Brotli-compressed
  - path: /unity/Build/*.data.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/*.framework.js.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/*.wasm.br
    name: Content-Encoding
    value: br
