staticPublishPath: ./dist

headers:
  - path: /unity/Build/*.data.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/*.data.br
    name: Content-Type
    value: application/octet-stream
  - path: /unity/Build/*.framework.js.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/*.framework.js.br
    name: Content-Type
    value: application/javascript
  - path: /unity/Build/*.wasm.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/*.wasm.br
    name: Content-Type
    value: application/wasm
