# render.yaml for Unity WebGL with Gzip
staticPublishPath: ./dist

headers:
  # Unity data
  - path: /unity/Build/*.data.unityweb
    name: Content-Encoding
    value: gzip
  - path: /unity/Build/*.data.unityweb
    name: Content-Type
    value: application/octet-stream

  # Unity framework JS
  - path: /unity/Build/*.framework.js.unityweb
    name: Content-Encoding
    value: gzip
  - path: /unity/Build/*.framework.js.unityweb
    name: Content-Type
    value: application/javascript

  # Unity WebAssembly
  - path: /unity/Build/*.wasm.unityweb
    name: Content-Encoding
    value: gzip
  - path: /unity/Build/*.wasm.unityweb
    name: Content-Type
    value: application/wasm
