staticPublishPath: ./dist

headers:
  # Unity Data (Brotli compressed)
  - path: /Build/*.data.unityweb
    values:
      Content-Type: application/octet-stream
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable

  # Unity Framework JS (Brotli compressed)
  - path: /Build/*.framework.js.unityweb
    values:
      Content-Type: application/javascript
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable

  # Unity WebAssembly (Brotli compressed)
  - path: /Build/*.wasm.unityweb
    values:
      Content-Type: application/wasm
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable
