staticPublishPath: ./dist

headers:
  # Unity Data (Brotli compressed)
  - path: /Build/*.data.unityweb
    values:
      Content-Type: application/octet-stream
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable

  # Unity Framework JS (Brotli compressed)
  - path: /Build/*.framework.js.unityweb
    values:
      Content-Type: application/javascript
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable

  # Unity WebAssembly (Brotli compressed)
  - path: /Build/*.wasm.unityweb
    values:
      Content-Type: application/wasm
      Content-Encoding: br
      Cache-Control: public, max-age=31536000, immutable

  # Apply CSP to all other paths
  - path: /*
    values:
      Content-Security-Policy: >
        default-src 'self' blob: data:;
        script-src 'self' 'unsafe-inline' 'unsafe-eval'
          https://auth.privy.io
          https://www.googletagmanager.com
          https://www.google-analytics.com
          https://www.googletagservices.com
          blob:;
        worker-src 'self' blob:;
        child-src 'self' blob: https://auth.privy.io;
        frame-src https://auth.privy.io;
        connect-src 'self' http://localhost:4173
          https://auth.privy.io
          https://www.googletagmanager.com
          https://www.google-analytics.com
          https://apster-backend.onrender.com
          https://explorer-api.walletconnect.com
          https://api.testnet.abs.xyz;
        style-src 'self' 'unsafe-inline';
        img-src 'self' data: https:;
