staticPublishPath: ./dist

headers:
  # Unity Data files (Brotli compressed)
  - path: /Build/*.data.br
    name: Content-Type
    value: application/octet-stream
  - path: /Build/*.data.br
    name: Content-Encoding
    value: br
  - path: /Build/*.data.br
    name: Cache-Control
    value: public, max-age=31536000, immutable

  # Unity Framework JS (Brotli compressed)
  - path: /Build/*.framework.js.br
    name: Content-Type
    value: application/javascript
  - path: /Build/*.framework.js.br
    name: Content-Encoding
    value: br
  - path: /Build/*.framework.js.br
    name: Cache-Control
    value: public, max-age=31536000, immutable

  # Unity WebAssembly (Brotli compressed)
  - path: /Build/*.wasm.br
    name: Content-Type
    value: application/wasm
  - path: /Build/*.wasm.br
    name: Content-Encoding
    value: br
  - path: /Build/*.wasm.br
    name: Cache-Control
    value: public, max-age=31536000, immutable

  # Fallback for uncompressed files (if any)
  - path: /Build/*.data
    name: Content-Type
    value: application/octet-stream
  - path: /Build/*.data
    name: Cache-Control
    value: public, max-age=31536000, immutable

  - path: /Build/*.framework.js
    name: Content-Type
    value: application/javascript
  - path: /Build/*.framework.js
    name: Cache-Control
    value: public, max-age=31536000, immutable

  - path: /Build/*.wasm
    name: Content-Type
    value: application/wasm
  - path: /Build/*.wasm
    name: Cache-Control
    value: public, max-age=31536000, immutable