# render.yaml for Unity WebGL + React with Brotli (nested folder workaround)
staticPublishPath: ./dist

headers:
  - path: /unity/Build/webBuild.data.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.data.br
    name: Content-Type
    value: application/octet-stream

  - path: /unity/Build/webBuild.framework.js.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.framework.js.br
    name: Content-Type
    value: application/javascript

  - path: /unity/Build/webBuild.wasm.br
    name: Content-Encoding
    value: br
  - path: /unity/Build/webBuild.wasm.br
    name: Content-Type
    value: application/wasm
