staticPublishPath: ./dist

headers:
  - path: /*
    values:
      Content-Security-Policy: >
        default-src 'self' blob: data:;
        script-src 'self' 'unsafe-inline' 'unsafe-eval'
          https://www.googletagmanager.com
          https://www.google-analytics.com
          https://auth.privy.io;
      X-Content-Type-Options: nosniff

routes:
  - type: rewrite
    source: /*
    destination: /index.html
